import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import { Grid } from '@mui/material'
import Header from './Component/Ui/Header'
import MobileNavBar from './Component/Ui/MobileNavBar'

const poppins = Poppins({
  weight: ["100", '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <style>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap');
        </style>
      </style>

      <body className={poppins.className}>
        <Grid container sx={{ justifyContent: 'center' }}>

          <Header />
          <MobileNavBar />

          {children}
        </Grid>
      </body>
    </html>
  )
}
