import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Grid } from '@mui/material'
import Header from './Component/Ui/Header'
import MobileNavBar from './Component/Ui/MobileNavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <style>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap');
        </style>
      </style>

      <body className={inter.className}>
        <Grid container sx={{ justifyContent: 'center' }}>

          <Header />
          <MobileNavBar />

          {children}
        </Grid>
      </body>
    </html>
  )
}
